name: Selenium Test Suite

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            browser: chrome
          - os: ubuntu-latest
            browser: firefox
          - os: windows-latest
            browser: chrome
          - os: windows-latest
            browser: firefox
          - os: windows-latest
            browser: edge

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Run Pytest tests
        run: |
          pytest --browser ${{ matrix.browser }} \
                 --alluredir=allure-results-${{ matrix.browser }}-${{ matrix.os }} \
                 --html=pytest-report-${{ matrix.browser }}-${{ matrix.os }}.html
        continue-on-error: true

      - name: Upload Pytest HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report-${{ matrix.browser }}-${{ matrix.os }}
          path: pytest-report-${{ matrix.browser }}-${{ matrix.os }}.html

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}-${{ matrix.os }}
          path: allure-results-${{ matrix.browser }}-${{ matrix.os }}/

  generate-report:
    needs: test
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Allure CLI
        run: |
          sudo apt-add-repository ppa:qameta/allure
          sudo apt-get update
          sudo apt-get install allure -y

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results-*
          path: allure-results
          merge-multiple: true

      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-report --clean
          allure open allure-report &

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
